# Generated by Django 5.0.6 on 2024-07-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={
                "ordering": ("username",),
                "verbose_name": "cook",
                "verbose_name_plural": "cooks",
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ("name",),
                "verbose_name": "dish",
                "verbose_name_plural": "dishes",
            },
        ),
    ]
